export const ACTIONS = {
  REGISTER_USER: "REGISTER_USER",

  REQUEST_FAKE_DATA: "REQUEST_FAKE_DATA",
  REQUEST_FAKE_DATA_SUCCEED: "REQUEST_FAKE_DATA_SUCCEED",
  REQUEST_FAKE_DATA_FAILED: "REQUEST_FAKE_DATA_FAILED",

  CHANGE_SELECTED_CATEGORY: "CHANGE_SELECTED_CATEGORY",

  CHANGE_ACTIVE_ITEM: "CHANGE_ACTIVE_ITEM"
};

export const CATEGORIES = {
  ALL: "0",
  TOP: "1",
  BOTTOM: "2",
  JACKET: "3",
  ACCESSORY: "4"
};

export const CART_STATUS = {
  SHOPPING: "0",
  CONFIRMED: "1",
  PREPARING: "2",
  PREPARED: "3",
  UPDATED: "4"
};

export const PRODUCT_STATUS = {
  ADDED: "0",
  NEW: "1",
  PREPARING: "2",
  PREPARED: "3"
};
