export const ACTIONS = {
  REGISTER_USER: "REGISTER_USER",

  REQUEST_FAKE_DATA: "REQUEST_FAKE_DATA",
  REQUEST_FAKE_DATA_SUCCEED: "REQUEST_FAKE_DATA_SUCCEED",
  REQUEST_FAKE_DATA_FAILED: "REQUEST_FAKE_DATA_FAILED",

  CHANGE_SELECTED_CATEGORY: "CHANGE_SELECTED_CATEGORY"
};

export const CATEGORIES = {
  ALL: "0",
  TOP: "1",
  BOTTOM: "2",
  JACKET: "3",
  ACCESSORY: "4"
};
